### ISSUE TITLE
feat: add, delete, view, mark as complete todo

### ISSUE THREAD

**Issue by MarJaysonSanAgustin** [MarJaysonSanAgustin/vue-simple-todo#1]
📋 Todo:
- [x] Add todo
- [x] Delete todo
- [x] List todo
- [x] Show completed todo
- [x] Mark todo as complete/incomplete
- [x] Toggle show completed todo
